name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Hacer checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Loguearse en Docker Hub
      run: |
        echo "Logueándose en Docker Hub..."
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}

    - name: Construir y subir la imagen de Docker
      uses: docker/build-push-action@v6.13.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: adriicl/calculadora:latest
        cache-from: type=registry,ref=adriicl/calculadora:latest
        cache-to: type=inline
