name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Hacer checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar PHP
        uses: shivammathur/setup-php@2.32.0
        with:
          php-version: "8.2"
          extensions: mbstring, pdo, pdo_mysql

      - name: Cache de dependencias de Composer
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-${{ runner.os }}-

      - name: Instalar dependencias
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Ejecutar tests
        run: vendor/bin/phpunit

  build:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Hacer checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Loguearse en Docker Hub
        run: |
          echo "Logueándose en Docker Hub..."
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Construir y subir la imagen de Docker (Multiplataforma)
        uses: docker/build-push-action@v6.13.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: adriicl/calculadora:latest
          cache-from: type=registry,ref=adriicl/calculadora:latest
          cache-to: type=inline
