name: Docker Image CI

on:
  push:
    tags:
      - "v*"

jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Hacer checkout del repositorio con todos los tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalar PHP
        uses: shivammathur/setup-php@2.32.0
        with:
          php-version: "8.2"
          extensions: mbstring, pdo, pdo_mysql

      - name: Instalar dependencias
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Ejecutar tests
        run: vendor/bin/phpunit --testdox tests

  build:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Hacer checkout del repositorio con todos los tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }} 

      - name: Obtener tag actual
        id: tag
        uses: olegtarasov/get-tag@v2.1.4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Loguearse en Docker Hub
        run: |
          echo "Logueándose en Docker Hub..."
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Construir y subir la imagen de Docker (Multiplataforma)
        uses: docker/build-push-action@v6.13.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            adriicl/calculadora:${{ steps.tag.outputs.tag }}
            adriicl/calculadora:latest
          cache-from: type=registry,ref=adriicl/calculadora:latest
          cache-to: type=inline
